apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web-backend-config
spec:
  # Web backend configuration
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backend-config
spec:
  # API backend configuration with CORS
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  # Enable CORS for API
  cors:
    allowOrigins:
      - "*"
    allowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    allowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    maxAge: 3600
    allowCredentials: false
