apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: worker
          image: us-central1-docker.pkg.dev/georgef-sandbox/keda-celery-flask-react/api:1.0.0-c097a5a0 # Use the same image as the API for consistency
          command:
            [
              "celery",
              "-A",
              "celery_app.celery",
              "worker",
              "-Q",
              "webhook",
              "--loglevel=INFO",
            ]
          env:
            - name: REDIS_HOST
              value: "redis"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
