apiVersion: v1
kind: Service
metadata: 
  name: web
spec:
  type: LoadBalancer
  ports: [{ port: 80, targetPort: 80 }]
  selector: { app: web }: v1
kind: Service
metadata:
  name: web
  annotations:
    cloud.google.com/backend-config: '{"default": "web-backend-config"}'
spec:
  type: NodePort
  ports: [{ port: 80, targetPort: 80, nodePort: 30081 }]
  selector: { app: web }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: web }
spec:
  replicas: 1
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
        - name: web
          image: us-central1-docker.pkg.dev/georgef-sandbox/keda-celery-flask-react/web:1.0.0-dc62ee1b
          ports: [{ containerPort: 80 }]
